# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache D:/Desktop/Project/five_stage_pipeLineCpu/.Xil/Vivado-4752-LAPTOP-CNUEB5OF/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.cache/wt [current_project]
set_property parent.project_path D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/stddef.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/ALU.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/CMP.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/Ctrl.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/DM.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/ExToMem.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/Foward.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/HazardUnit.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/IM.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/IdToEx.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/IfToId.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/MFA.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/MFB.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/MemToWb.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/NPC.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/PC.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/Rf.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/exp.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/stall_creat.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/stall_solve.v
  D:/Desktop/Project/five_stage_pipeLineCpu/five_stage_pipeLineCpu.srcs/sources_1/new/pipelinecpu.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top pipelinecpu -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pipelinecpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pipelinecpu_utilization_synth.rpt -pb pipelinecpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
